### ISSUE TITLE
iPad: Send Button not visible in windowed mode

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#2886]
> This issue was **originally reported in the forum**: https://support.delta.chat/t/chat-send-button-not-visible-on-ipad-app-in-windowed-mode/4317 (I asked there for the missing info (dc version and ipad model))

- iOS version: iPad OS 26.1
- Device: ipad model ???
- Delta Chat version: ???
- Expected behavior: send button is visible in windowed mode
- Actual behavior: send button is often out of bounds or invisible
- Steps to reproduce the problem:
   - opening a chat (not after fresh start but most often later on) does not show the message entry box and / or the send button.
   - Workaround is closing and restarting the Delta Chat App on iPad OS.
- Screenshots:

<img  height="500" alt="Image" src="https://github.com/user-attachments/assets/e3c085b4-b8e2-4298-b5f0-d5a600421a7a" />

**Comment by agaagaug** [comment]
Same issue here and more. Testing the windowed mode on iPads is necessary. 
At some point, leaving the app in the background, using it again after a while, the message entry box overlaps the last chat bubble, too. 
It seems to not happen with a "fresh started instance". But over time.

**Comment by Amzd** [comment]
This will be fixed with input bar rewrite for liquid glass.

**Comment by Amzd** [comment]
Tested on simulator and this seems fixed since the liquid glass PR #2973

**Comment by r10s** [comment]
is this one fixed by chance as well? https://support.delta.chat/t/ipad-account-switcher-inaccessible-unless-rotating-ipad/5489

**Comment by Amzd** [comment]
@r10s there is not any specific steps on how to trigger the bug they experienced but I can't reproduce the symptom

**Comment by agaagaug** [comment]
Unfortunately I'm seeing both issues still happening on an iPad latest OS 26.5. 

Note: This is all happening while in windowed mode or stage manager mode AND the window size isn't full size. 

1. The text input box disappears partly or completely making it impossible to respond to a message, because the send button isn't visible anymore, or the entire box is missing. This happens not as often as below.

2. The account switcher at the top left isn't showing, instead return to "chats" (<chats) is showing, which I am already. Touching/clicking on <chats doesn't do anything. 

Workaround still: kill and re-launch app.

**Comment by Amzd** [comment]
On master branch? @agaagaug

**Comment by agaagaug** [comment]
Sorry, I'm not part of the dev team. I'm just a user of the app. I'm using version (shown under settings in the iPadOS app) 2.53.0. 
Apologies if I mixed things up.

**Comment by r10s** [comment]
there is 2.53.1 available on testflight since some minutes, that contains the fixes that closes this issue - and maybe the one from the forum

https://testflight.apple.com/join/uEMc1NxS

**Comment by agaagaug** [comment]
Can I ignore the warning, if I use TestFlight that my chats might be deleted? 
Will a Backup be "good enough" to prevent loss of data?

**Comment by Amzd** [comment]
Yes just create a backup and move it out of the DeltaChat folder in Files, and you're safe.
